channels:
  - defaults
  - conda-forge
dependencies:
  - python>=3.7.6,<3.10
  - numpy>=1.19.5,<2
  - pandas>=1.1.3
  - scikit-learn>=1.2
  - numba>=0.52.0
  - umap-learn>=0.3.9
  - optuna>=2.10.0
  - psutil>=5.7.3
  - anytree>=2.8.0
  - matplotlib>=3.3.3
  - seaborn>=0.11.0
  - pip=22.2.2
  - pip:
     - scikit-network>=0.20.0
